### ISSUE TITLE
Still useful with supported versions of Django?

### ISSUE THREAD

**Issue by moseb** [bancek/django-smtp-ssl#3]
Hi!

I saw someone use this module in new 2019 code and hence had a closer look. My understanding is that you added a custom SMTP SSL backend in 2011 because it was only introduced to Django upstream in 2013 https://github.com/django/django/commit/59ebe39812858ba37e83ab0ee886f676980d472d.

Does `django-smtp-ssl` offer something today that recent Django does not that I'm overlooking? If not, maybe marking this project as obsolete would help the community. What do you think? 

Best, Sebastian

**Comment by bancek** [comment]
Yes, this project is now obsolete. Can you open a pull request to add the notice to the README?

**Comment by moseb** [comment]
Here you go: #3

**Comment by bancek** [comment]
Thank you.
